object frmSelect: TfrmSelect
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 120
  BorderStyle = bsNone
  Caption = 'frmSelect'
  ClientHeight = 485
  ClientWidth = 746
  Color = clNavy
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  OnMouseUp = FormMouseUp
  PixelsPerInch = 96
  TextHeight = 13
end
